function [MM, DM, DD] = readData_18_fn(A)

    [error_1, error_2, error_3, error4, ...
        error_5, error_6, error_7, error8, ...
        error_9, error_10, error_11, error12, ...
        error_13, error_14, error_15, error16, ...
        error_17, error_18, ...        
        ] = textread(A,'%n %n %n %n %n  %n %n %n %n %n  %n %n %n %n %n  %n %n %n','headerlines',1);

    MM = [error_1, error_2, error_3, error4, ...
        error_5, error_6, error_7, error8, ...
        error_9, error_10, error_11, error12, ...
        error_13, error_14, error_15, error16];
    DM = error_17;
    DD = error_18;
end




